# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 杨小米
subtitle: 做一枚安静的咸鸭蛋，闲的要命，富的流油。
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Talk is cheap,Show me the code.</a>
description: > # this means to ignore newlines until "baseurl:"
  白日梦想家.
email: huqing758@163.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:title/
twitter_username: jekyllrb
github_username:  yslahq

# Build settings
markdown: rdiscount
theme: minima
gems:
  - jekyll-feed

pygments: true

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Resume, description: My Resume, url: 'https://yslahq.github.io/resume/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Social
social:
    github: yslahq
    mail: huqing758@163.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude: [vendor]
